runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:

    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://HOST:47@/sensorData?unix_socket=/cloudsql/ec463-group47:northamerica-northeast1:instance

beta_settings:
    cloud_sql_instances: ec463-group47:northamerica-northeast1:instance
