name: ci

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: pip install flake8
    - run: flake8 --extend-ignore=W,E1,E2,E3,E5
